---
- name: Copy nginx.conf with owner and permissions
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'

- name: Copy nginx and config  with owner and permissions
  ansible.builtin.copy:
    src: default_server1.conf
    dest: /etc/nginx/conf.d/default_server.conf
    owner: nginx
    group: nginx
    mode: '0644'

- name: Copy public cert with owner and permissions
  ansible.builtin.copy:
    src: certificate.pem
    dest: /etc/nginx/certificate.pem
    owner: nginx
    group: nginx
    mode: '0644'

- name: Copy private key with owner and permissions
  ansible.builtin.copy:
    src: key.pem
    dest: /etc/nginx/key.pem
    owner: nginx
    group: nginx
    mode: '0644'

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: www.conf
    dest: /etc/php-fpm.d/www.conf
#    dest: /usr/share/nginx/html/wordpress/www.conf
    owner: nginx
    group: nginx
    mode: '0644'

- name: Change Ownership of wordpress files
  file:
    path: "{{ wordpress_directory_path }}"
    owner: nginx
#    group: nginx
    mode: '0755'
    state: directory
    recurse: yes
  notify:
  - restart nginx

- name: Change Ownership of var lib php
  file:
    path: /usr/share/nginx/html/wordpress
    owner: nginx
    group: nginx
    mode: '0755'
    state: directory
    recurse: yes
  notify:
  - restart php
