---
- name: Download wordpress
  get_url:
    url: https://wordpress.org/latest.tar.gz
    dest: /usr/share/nginx/html/latest.tar.gz
- name: Unzip wordpress
  unarchive:
    src: /usr/share/nginx/html/latest.tar.gz
    dest: /usr/share/nginx/html/
    remote_src: yes
- name: Copy nginx and config  with owner and permissions
  ansible.builtin.copy:
    src: wp-config.php
    dest: /usr/share/nginx/html/wordpress/wp-config.php
    owner: nginx
    group: nginx
    mode: '0644'
