---
#- name: Install db server
#  hosts: db_server 
#  become: true
#  roles:
#    - db

- name: Install load balance servers
  hosts: balance_servers
  become: true
  roles:
    - lb

#- name: Mount iscsi drive
#  hosts: gfs2
#  become: true
#  roles:
#    - iscsi-initiators
