---
- name: Ensure hostname set
  hosts: all
  become: true
  tasks:
    - ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    - name: Configure hosts file
      copy:
        src: hosts
        dest: /etc/hosts
        owner: root
        group: root
        mode: 0644
        backup: yes

- name: Install db server
  hosts: db_server 
  become: true
  roles:
    - db

- name: Install load balance servers
  hosts: balance_servers
  become: true
  roles:
    - lb

- name: Install and configure web serverse
  hosts: web_servers
  become: true
  roles:
    - web
