---
- name: NGINX | Config NGINX config file from template
  template:
    src: templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/nginx.conf
  notify:
    - reload nginx
  tags:
    - nginx-configuration
