---
- name: check OS version
  fail: msg='OS is NOT CentOS 7.x'
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '7'

- name: install iscsi server package CentOS
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - targetcli
