---
- name: Check that the somefile.conf exists
  stat:
    path: /etc/iscsi.lock
  register: stat_result

- name: Abort if lock file exists
  fail: msg='iscsi-server is already configured'
  when: stat_result.stat.exists

- name: Configuring iscsi-server (step 1)
  shell: "{{ item }}"
  with_items:
    - " hostnamectl set-hostname iscsi-server"
    - ' targetcli backstores/block create drive01 /dev/$(lsblk|tail -n 1|cut -d" " --fields=1)'
    - " targetcli /iscsi create iqn.$(date +%Y-%m).internal.auto.$(hostname):storage.target00"
    - " targetcli /iscsi/iqn.$(date +%Y-%m).internal.auto.$(hostname):storage.target00/tpg1/luns create /backstores/block/drive01"
#    - " pcs cluster auth {{ nodelist }} -u hacluster -p {{ pcm_password }}"
#  no_log: true

- name: create lock file
  file: 
    path: /etc/iscsi.lock
    state: touch
