---
- name: check OS version
  fail: msg='OS is NOT CentOS 7.x'
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '7'

- name: install iscsi packages CentOS
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - pacemaker
    - pcs
    - resource-agents
    - corosync 
    - fence-agents-all.x86_64
    - psmisc 
    - policycoreutils-python
     
- name: enable pcsd service
  systemd:
    name: pcsd
    state: started
    enabled: yes

