---
- name: Install iSCSI client
  hosts: gfs2
  become: true
  roles:
    - iscsi-client 

- name: Install iSCSI server
  hosts: iscsi-server
  become: true
  roles:
    - iscsi-server

- name: Mount iscsi drive
  hosts: gfs2
  become: true
  roles:
    - iscsi-initiators
