---
- name: 
  shell: "{{ item }}"
  loop:
    - " pcs cluster start --all"
    - " pcs property set stonith-enabled=false"
    - " pcs property set no-quorum-policy=freeze"
    - " pcs resource create dlm systemd:dlm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
    - " pcs resource create clvmd ocf:heartbeat:clvm op monitor interval=30s on-fail=ignore clone interleave=true ordered=true"
    - " pcs constraint order start dlm-clone then clvmd-clone"
    - " sleep 5"
    - " pvcreate /dev/sda"
    - " sleep 50"
    - " vgcreate -Ay -cy cluster_vg /dev/sda"
    - " lvcreate -L900M -n cluster_lv cluster_vg"
    - " yes y|mkfs.gfs2 -j{{ hosts_in_cluster }} -p lock_dlm -t {{ pacemaker_hacluster_name }}:gfs2 /dev/cluster_vg/cluster_lv"
    

