---
- name: check OS version
  fail: msg='OS is NOT CentOS 7.x'
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '7'

# Nginx installation
- name: Install remi repo.
  yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-{{ ansible_distribution_major_version }}.rpm
    state: present

- name: Import remi GPG key.
  rpm_key:
    key: http://rpms.remirepo.net/RPM-GPG-KEY-remi
    state: present

- name: Enable php72 repo
  ini_file:
    dest: /etc/yum.repos.d/remi-php72.repo
    section: remi-php72
    option: enabled
    value: 1

- name: Download and Install MySQL repo
  yum: name=https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm

# tasks file for nginx
- name: Install EPEL, NGINX, and osther packages
  yum:
    name: "{{ item }}"
    state: present
  loop:
    - epel-release
    - nginx
    - vim
    - wget
    - php
    - php-cli
    - php-fpm
    - php-mysql
    - php-json
    - php-opcache
    - php-mbstring
    - php-curl
    - php-gd
    - php-intl
    - php-soap
    - php-xml
    - php-xmlrpc
    - php-zip
    - setroubleshoot-server-3.2.30-8.el7.x86_64
    - mysql
    - mysql-router
#  notify:
#    - restart php
  tags:
    - packages

#- name: Install PyMySQL python package
#  pip:
#    name: PyMySQL
#- name: Configure hosts file
#  copy:
#    src: hosts
#    dest: /etc/hosts
#    owner: root
#    group: root
#    mode: 0644
#    backup: yes
