---
- name: check OS version
  fail: msg='OS is NOT CentOS 7.x'
  when: ansible_distribution != 'CentOS' or ansible_distribution_major_version != '7'

- name: install iscsi packages CentOS
  yum: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - iscsi-initiator-utils
    - iscsi-initiator-utils-iscsiuio
    - device-mapper-multipath
    - gfs2-utils
    - lvm2-cluster
    - fence-agents-all
# - name: install iscsi target package Ubuntu
#   apt: name={{ item }}
#   state: present
#   with_items:
#     - targetcli
#
